// Generated by TKG at 2017-05-15 18:03:31

#include "keymap_common.h"

#define KEYMAP_TKG( \
    K0A, K0B, K0C, K0D, K0E, K0F, K0G, K0H, K0I, K0J, K0K, K0L, K0M, K0N, K0O, \
    K1A, K1B, K1C, K1D, K1E, K1F, K1G, K1H, K1I, K1J, K1K, K1L, K1M, K1N, K1O, \
    K2A, K2B, K2C, K2D, K2E, K2F, K2G, K2H, K2I, K2J, K2K, K2L, K2M, K2N, K2O, \
    K3A, K3B, K3C, K3D, K3E, K3F, K3G, K3H, K3I, K3J, K3K, K3L, K3M, K3N, K3O, \
    K4A, K4B, K4C,                     K4H,      K4J, K4K,      K4M, K4N, K4O, \
         K5B, K5C, K5D, K5E, K5F, K5G, K5H, K5I, K5J, K5K  \
) { \
    { KC_##K0A, KC_##K0B, KC_##K0C, KC_##K0D, KC_##K0E, KC_##K0F, KC_##K0G, KC_##K0H, KC_##K0I, KC_##K0J, KC_##K0K, KC_##K0L, KC_##K0M, KC_##K0N, KC_##K0O, KC_NO,    KC_NO,    KC_NO    }, \
    { KC_##K1A, KC_##K1B, KC_##K1C, KC_##K1D, KC_##K1E, KC_##K1F, KC_##K1G, KC_##K1H, KC_##K1I, KC_##K1J, KC_##K1K, KC_##K1L, KC_##K1M, KC_##K1N, KC_##K1O, KC_NO,    KC_NO,    KC_NO    }, \
    { KC_##K2A, KC_##K2B, KC_##K2C, KC_##K2D, KC_##K2E, KC_##K2F, KC_##K2G, KC_##K2H, KC_##K2I, KC_##K2J, KC_##K2K, KC_##K2L, KC_##K2M, KC_##K2N, KC_##K2O, KC_NO,    KC_NO,    KC_NO    }, \
    { KC_##K3A, KC_##K3B, KC_##K3C, KC_##K3D, KC_##K3E, KC_##K3F, KC_##K3G, KC_##K3H, KC_##K3I, KC_##K3J, KC_##K3K, KC_##K3L, KC_##K3M, KC_##K3N, KC_##K3O, KC_NO,    KC_NO,    KC_NO    }, \
    { KC_##K4A, KC_##K4B, KC_##K4C, KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_##K4H, KC_NO,    KC_##K4J, KC_##K4K, KC_NO,    KC_##K4M, KC_##K4N, KC_##K4O, KC_NO,    KC_NO,    KC_NO    }, \
    { KC_NO,    KC_##K5B, KC_##K5C, KC_##K5D, KC_##K5E, KC_##K5F, KC_##K5G, KC_##K5H, KC_##K5I, KC_##K5J, KC_##K5K, KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO    }  \
}

#ifdef KEYMAP_SECTION_ENABLE
const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] __attribute__ ((section (".keymap.keymaps"))) = {
#else
const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] PROGMEM = {
#endif
    [0] = KEYMAP_TKG(
        ESC, 1,   2,   3,   4,   5,   6,   7,   8,   9,   0,   MINS,EQL, BSLS,HOME, \
        TAB, Q,   W,   E,   R,   T,   Y,   U,   I,   O,   P,   LBRC,RBRC,BSPC,PGUP, \
        LCTL,A,   S,   D,   F,   G,   H,   J,   K,   L,   SCLN,QUOT,GRV, ENT, PGDN, \
        LSFT,FN0, Z,   X,   C,   V,   B,   N,   M,   COMM,DOT, SLSH,RSFT,UP,  END,  \
        LCTL,LALT,LGUI,                    FN11,     SPC, RALT,     LEFT,DOWN,RGHT, \
             FN1, FN2, FN3, FN4, FN5, FN6, FN7, FN8, FN9, FN10),
    [1] = KEYMAP_TKG(
        TRNS,F1,  F2,  F3,  F4,  F5,  F6,  F7,  F8,  F9,  F10,   F11,F12, TRNS,TRNS, \
        CAPS, TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   PSCR,   SLCK,PAUS, DEL,TRNS, \
        TRNS,TRNS,   TRNS,   TRNS,   PGDN,   TRNS,LEFT,DOWN,  UP,RGHT,   TRNS,TRNS,TRNS, TRNS, TRNS, \
        TRNS,FN0, TRNS,   TRNS,   TRNS,   TRNS,   PGUP,   TRNS,   TRNS,   TRNS,TRNS, TRNS,TRNS,TRNS,  TRNS,  \
        TRNS,TRNS,TRNS,                    TRNS,     FN23, TRNS,     TRNS,TRNS,TRNS, \
             FN24, FN25, FN26, FN27, FN28, FN29, FN30, FN31, TRNS, TRNS),
    [2] = KEYMAP_TKG(
        TRNS, F1,   F2,   F3,   F4,   F5,   F6,   F7,   F8,   F9,   F0,   F11,F12, TRNS,TRNS, \
        CAPS, VOLU,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,TRNS,DEL,TRNS, \
        TRNS,MUTE,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,TRNS,TRNS, TRNS, TRNS, \
        TRNS,TRNS, VOLD,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,   TRNS,TRNS, TRNS,TRNS,TRNS,  TRNS,  \
        TRNS,TRNS,TRNS,                    TRNS,     FN22, RALT,     LEFT,DOWN,RGHT, \
             FN12, FN13, FN14, FN15, FN16, FN17, FN18, FN19, FN20, FN21),
    [3] = KEYMAP_TKG(
        ESC,1,  2,  3,  4,  5,  6,  7,  8,  9,  0,   TRNS,TRNS, TRNS,TRNS, \
        TAB, Q,   W,   E,   R,   T,   Y,   U,   I,   O,   P,   LBRC,RBRC,BSPC,PGUP, \
        LCTL,A,   S,   D,   F,   G,   H,   J,   K,   L,   SCLN,QUOT,GRV, ENT, PGDN, \
        LSFT,FN0, Z,   X,   C,   V,   B,   N,   M,   COMM,DOT, SLSH,RSFT,UP,  END,  \
        CAPS,LGUI,LALT,                    FN11,     SPC, RALT,     LEFT,DOWN,RGHT, \
             FN12, FN13, FN14, FN15, FN16, FN17, FN18, FN19, FN20, FN21),
};

enum macro_id{
    M1,
    M2,
    M3,
    M4,
    M5,
    M6,
    M7,
    M8,
    M9,
    M0,
    QQQ,
    WWW,
    EEE,
    QQE,
    QQW,
    QEE,
    QWW,
    QWE,
    EEW,
    WWE
};

const macro_t *action_get_macro(keyrecord_t * rec, uint8_t id, uint8_t op){
    keyevent_t event = rec->event;
    switch(id){
        case QQQ:
            return (event.pressed ?
                MACRO(T(Q), T(Q), T(Q), T(R), END ) :
                MACRO(END) );
        case WWW:
            return (event.pressed ?
                MACRO(T(W), T(W), T(W), T(R), END ) :
                MACRO(END) );
        case EEE:
            return (event.pressed ?
                MACRO(T(E), T(E), T(E), T(R), END ) :
                MACRO(END) );
        case QQE:
            return (event.pressed ?
                MACRO(T(Q), T(Q), T(E), T(R), END ) :
                MACRO(END) );
        case QQW:
            return (event.pressed ?
                MACRO(T(Q), T(Q), T(W), T(R), END ) :
                MACRO(END) );
        case QEE:
            return (event.pressed ?
                MACRO(T(Q), T(E), T(E), T(R), END ) :
                MACRO(END) );
        case QWW:
            return (event.pressed ?
                MACRO(T(Q), T(W), T(W), T(R), END ) :
                MACRO(END) );
        case QWE:
            return (event.pressed ?
                MACRO(T(Q), T(W), T(E), T(R), END ) :
                MACRO(END) );
        case EEW:
            return (event.pressed ?
                MACRO(T(E), T(E), T(W), T(R), END ) :
                MACRO(END) );
        case WWE:
            return (event.pressed ?
                MACRO(T(W), T(W), T(E), T(R), END ) :
                MACRO(END) );
        case M0:
            return (event.pressed ?
                MACRO(T(0), END) :
                MACRO(END) );
        case M1:
            return (event.pressed ?
                MACRO(T(1), END) :
                MACRO(END) );
        case M2:
            return (event.pressed ?
                MACRO(T(2), END) :
                MACRO(END) );
        case M3:
            return (event.pressed ?
                MACRO(T(3), END) :
                MACRO(END) );
        case M4:
            return (event.pressed ?
                MACRO(T(4), END) :
                MACRO(END) );
        case M5:
            return (event.pressed ?
                MACRO(T(5), END) :
                MACRO(END) );
        case M6:
            return (event.pressed ?
                MACRO(T(6), END) :
                MACRO(END) );
        case M7:
            return (event.pressed ?
                MACRO(T(7), END) :
                MACRO(END) );
        case M8:
            return (event.pressed ?
                MACRO(T(8), END) :
                MACRO(END) );
        case M9:
            return (event.pressed ?
                MACRO(T(9), END) :
                MACRO(END) );
    }
    return MACRO_NONE;
}

#ifdef KEYMAP_SECTION_ENABLE
const uint16_t fn_actions[] __attribute__ ((section (".keymap.fn_actions"))) = {
#else
const uint16_t fn_actions[] PROGMEM = {
#endif
    [0] = ACTION_LAYER_MOMENTARY(1),
    [1] = ACTION_MACRO(M1),
    [2] = ACTION_MACRO(M2),
    [3] = ACTION_MACRO(M3),
    [4] = ACTION_MACRO(M4),
    [5] = ACTION_MACRO(M5),
    [6] = ACTION_MACRO(M6),
    [7] = ACTION_MACRO(M7),
    [8] = ACTION_MACRO(M8),
    [9] = ACTION_MACRO(M9),
    [10] = ACTION_MACRO(M0),
    [11] = ACTION_LAYER_MOMENTARY(2),
    [12] = ACTION_MACRO(QQQ),
    [13] = ACTION_MACRO(QEE),
    [14] = ACTION_MACRO(EEE),
    [15] = ACTION_MACRO(QQW),
    [16] = ACTION_MACRO(QWW),
    [17] = ACTION_MACRO(WWE),
    [18] = ACTION_MACRO(QWE),
    [19] = ACTION_MACRO(WWW),
    [20] = ACTION_MACRO(EEW),
    [21] = ACTION_MACRO(QQE),
    [22] = ACTION_LAYER_TOGGLE(3),
    [23] = ACTION_LAYER_TOGGLE(1),
    [24] = ACTION_FUNCTION(2, ),
    [25] = ACTION_FUNCTION(3, ),
    [26] = ACTION_FUNCTION(4, ),
    [27] = ACTION_FUNCTION(7, ),
    [28] = ACTION_FUNCTION(7, 1),
    [29] = ACTION_BACKLIGHT_INCREASE(),
    [30] = ACTION_BACKLIGHT_DECREASE(),
    [31] = ACTION_BACKLIGHT_TOGGLE(),
};
